---
platform: linux

inputs:
- name: service-account-tf

outputs:
- name: service-account-json

run:
  path: bash
  args:
  - -euc
  - |
    jq -r '.key' service-account-tf/metadata | base64 --decode > service-account-json/gcreds.json
