---
platform: linux

inputs:
- name: service-account-tf
- name: bbl-state

outputs:
- name: bbl-state

run:
  path: bash
  args:
  - -euc
  - |
    jq -r '.key' service-account-tf/metadata | base64 --decode > bbl-state/gcreds.json
