---
platform: linux

inputs:
- name: setup-tf
- name: bbl-state

outputs:
- name: bbl-state

run:
  path: bash
  args:
  - -euc
  - |
    jq -r '.service_account_key' setup-tf/metadata | base64 --decode > bbl-state/gcreds.json
    jq -r '.certificate' setup-tf/metadata > bbl-state/tls_cert
    jq -r '.private_key' setup-tf/metadata > bbl-state/tls_key
