---
platform: linux

params:
  GCP_CREDENTIALS_JSON:
  PROJECT_ID:

run:
  path: bash
  args:
  - -euc
  - |
    echo "${GCP_CREDENTIALS_JSON}" > googlecreds.json
    export gcreds=$PWD/googlecreds.json
    gcloud auth activate-service-account --key-file="$gcreds"

    mkdir -p base-state
    pushd base-state
      git init
    popd

    tar czf state.tgz -C base-state .

    gsutil ls gs://${PROJECT_ID}/bbl || \
      gsutil cp state.tgz gs://${PROJECT_ID}/bbl/
